apiVersion: v1
kind: List
metadata:
  name: rhcos-vpcgen2-ignitiondata-list
  annotations:
    version: (( grab $TRAVIS_COMMIT || "dev" ))
    razee.io/source-url: (( grab $REPO_SOURCE_URL || "razee.io/source-url" ))
    razee.io/build-url: (( grab $BUILD_URL || "razee.io/build-url" ))
items:
  - apiVersion: v1
    kind: ConfigMap
    data:
      releaseimage: "{{ DOCKER_REGISTRY }}/armada-master/ocp-release:4.8.0-fc.1-x86_64"
    metadata:
      name: "{{managed_cluster_tail}}-nodepool-metadata-info"
      namespace: master
  - apiVersion: v1
    kind: ConfigMap
    data:
      data:
        (( file "tmp/machine-configs/ibm-payload-base.yaml.based" ))
    metadata:
      name: ignition-config-97-ibm-machineconfig-base
      namespace: master-{{managed_cluster_tail}}
      labels:
        ignition-config: "true"
  - apiVersion: v1
    kind: ConfigMap
    data:
      data:
        (( file "tmp/machine-configs/ibm-private-additions.yaml.based" ))
    metadata:
      name: ignition-config-98-ibm-machineconfig-private
      namespace: master-{{managed_cluster_tail}}
      labels:
        ignition-config: "true"
  - apiVersion: v1
    kind: ConfigMap
    data:
      data:
        (( file "tmp/machine-configs/ibm-ntp-vpcgen2.yaml.based" ))
    metadata:
      name: ignition-config-98-ibm-machineconfig-chrony
      namespace: master-{{managed_cluster_tail}}
      labels:
        ignition-config: "true"
  - apiVersion: v1
    kind: ConfigMap
    data:
      data:
        (( file "tmp/machine-configs/ibm-satellite-additions.yaml.based" ))
    metadata:
      name: ignition-config-99-ibm-machineconfig-satellite
      namespace: master-{{managed_cluster_tail}}
      labels:
        ignition-config: "true"
  - apiVersion: v1
    kind: ConfigMap
    data:
      data: |
        apiVersion: operator.openshift.io/v1alpha1
        kind: ImageContentSourcePolicy
        metadata:
          name: ibm-registry
        spec:
          repositoryDigestMirrors:
          - mirrors:
            - private.{{ kubx-masters.armada-info-configmap.ICR_REGISTRY_URL }}/armada-master/ocp-release
            source: quay.io/openshift-release-dev/ocp-release
          - mirrors:
            - private.{{ kubx-masters.armada-info-configmap.ICR_REGISTRY_URL }}/armada-master/ocp-release
            source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    metadata:
      name: ignition-config-98-ibm-registry-mirror
      namespace: master-{{managed_cluster_tail}}
      labels:
        ignition-config: "true"
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{managed_cluster_tail}}-ibm-nodepool-reconcile"
      namespace: master
      labels:
        app: ibm-nodepool-reconcile
      annotations:
        version: (( grab $TRAVIS_COMMIT || "dev" ))
        razee.io/source-url: (( grab $REPO_SOURCE_URL ))
        razee.io/build-url: (( grab $BUILD_URL ))
    spec:
      template:
        metadata:
          name: "{{managed_cluster_tail}}-ibm-nodepool-reconcile"
        spec:
          serviceAccount: ibm-nodepoolreconciler
          tolerations:
            - key: dedicated
              operator: Equal
              value: armada
              effect: NoSchedule
            - key: multi-az-worker
              operator: Equal
              value: "true"
              effect: NoSchedule
          containers:
            - name: nodepool-reconcile
              image: (( concat "{{ DOCKER_REGISTRY }}/armada-master/rhcos-vpcgen2-ignitiondata:" metadata.annotations.version ))
              command: ['/bin/bash', '-c', '/usr/local/bin/reconcile_nodepool_metadata.sh']
              env:
                - name: NODE_POOL_NAMESPACE
                  value: "master"
                - name: HOSTED_CLUSTERID
                  value: "{{managed_cluster_tail}}"
                - name: RELEASE_IMAGE
                  valueFrom:
                    configMapKeyRef:
                      name: "{{managed_cluster_tail}}-nodepool-metadata-info"
                      key: releaseimage
          restartPolicy: Never
